server:
    port: 44000
spring:
  application:
      name: test‐rabbitmq‐producer
  rabbitmq:
      host: 10.19.105.122
      port: 5672
      username: admin
      password: admin
      virtualHost: /
